[build]
# target the hypothetical x86_64-v7em architecture
# loosely based on ARM
target = "x86_64-v7em.json"

# [target.'cfg(target_os = "none")']
# runner = "bootimage runner"

[unstable]
# core and compiler_builtins need to be recompiled for x86_64-v7em
# memory allocation features from Rust's standard library need to be rebuilt as well
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]